#!/bin/bash
#PBS -P vy72
#PBS -N bulk_orientations
#PBS -q express
#PBS -l walltime=24:00:00,mem=192GB,ncpus=48,jobfs=50GB
#PBS -l storage=scratch/rxh562+gdata/ha3
#PBS -l wd
#PBS -j oe
#PBS -M rakib.hassan@ga.gov.au
#PBS -m bae

module purge
module load pbs
module load python3-as-python
module load openmpi/3.1.4
module load hdf5/1.10.5p
module load geos

export PATH=$HOME/.local/bin:$PATH
export PYTHONPATH=/g/data/ha3/rakib/seismic/pst/hiperseis/:$PYTHONPATH
export LC_ALL=en_AU.UTF-8
export LANG=en_AU.UTF-8

mpirun -np 48 python /g/data/ha3/rakib/seismic/pst/hiperseis/seismic/bulk_station_orientations.py /g/data/ha3/Passive/SHARED_DATA/DataQuality/Orientation/OA/OA_waveforms_20170911T000036-20210401T053646.h5 'OA' --output-basename /g/data/ha3/Passive/SHARED_DATA/DataQuality/Orientation/OA/OA_orientations


