#!/usr/bin/env python

import os

from seismic.inventory import engd2stxml
from seismic.inventory.engd2stxml import rt_timestamp


def test_engd2stxml_main(tmp_path):
    """Test main entry point for STN file conversion

    :param tmp_path: Path in which to store output files, auto-generated by pytest
    :type tmp_path: str or pathlib.Path
    """
    assert not os.path.exists(os.path.join(str(tmp_path), "INVENTORY_" + rt_timestamp + ".xml"))
    self_path = os.path.dirname(os.path.abspath(__file__))
    test_data_path = os.path.join(self_path, 'data')
    stations_folder = os.path.join(test_data_path, 'stations')
    engd2stxml.main(os.path.join(test_data_path, "IRIS-ALL_tiny.xml"),
                    stations_folder, str(tmp_path), test_mode=True)
    assert os.path.exists(os.path.join(str(tmp_path), "INVENTORY_" + rt_timestamp + ".xml"))

# TODO: Add additional test functions that:
#   * test individual functions from engd2stxml module
#   * test the correctness of the content in the output INVENTORY_*.xml file
